### ISSUE TITLE
Message: 'geckodriver' executable needs to be in PATH. 

### ISSUE THREAD

**Issue by davien** [Entromorgan/Autoticket#1]
MAC Python 3.7.2, 报的这个错，我尝试使用谷歌浏览器，webdriver.Chrome()解决了。

**Comment by Entromorgan** [comment]
我的测试环境是Win10+Python 3.6.2，没用Chrome是因为当时没找到匹配最新版本的driver，不确定直接换webdriver.Chrome()能直接用
