### ISSUE TITLE
指定抢票数量

### ISSUE THREAD

**Issue by Mrwrichard** [Entromorgan/Autoticket#11]
你好，我改了下多张票的代码，简单试了下好像能用
`ticket_limit = self.driver.find_element_by_class_name('number_right_limit')
            print('{}'.format(ticket_limit.text))
            print('设定购买{}张'.format(self.ticket_num))

            if self.ticket_num > 1:# 自动添加购票数
                add = self.driver.find_element_by_class_name('cafe-c-input-number-handler-up')
                while add.is_displayed() != True: # 等待显示
                    continue
                for i in range(self.ticket_num-1):
                    add.click()  `

**Comment by Entromorgan** [comment]
这部分我在注释里写了，如果在真实的抢票场景中，我们可能要先不断刷新等待抢票按钮出现，这个时候这段添加购票数的代码是有问题的，因为页面中不会出现增加票数的按钮，所以前面需要添加抢票按钮的判断。

**Comment by charleslck** [comment]
不是可以只有当按钮文字变成'立即购买'的情况下再去判断有无增加票数的按钮吗？

**Comment by Entromorgan** [comment]
可以的，这部分逻辑我暂时没有补充，你们可以自己加上~

**Comment by wangmoi** [comment]
请问买多张票的话如何勾选多个观影人呢？ label找到两个后分别命名 然后find_element_by_tag_name('input').click() 会先点击第一个然后取消勾选再点击第二个 请问这个是什么情况？

**Comment by wangmoi** [comment]
已解决...
