### ISSUE TITLE
改动代码运行闪退

### ISSUE THREAD

**Issue by Zing128** [Entromorgan/Autoticket#12]
改动的只有config.json里面的内容吧，我改了一点，运行了一半，抢票过程中闪退了

**Comment by Zing128** [comment]
还想问只能支持pc端，手机的不可以么

**Comment by Entromorgan** [comment]
改动的只有config.json。闪退是指浏览器闪退吧？代码逻辑中是有出错关闭浏览器的，具体的问题需要把终端输出的内容贴上来才能确定。这个工具还处于比较初级的阶段，不太稳定...目前无法支持手机端。

**Comment by Zing128** [comment]
最新消息，我去试了周杰伦，失败了/(ㄒoㄒ)/~~

**Comment by Gavin12340** [comment]
> 
> 
> 最新消息，我去试了周杰伦，失败了/(ㄒoㄒ)/~~

还没来得及用，以为能抢成功呢？

**Comment by ycyranqingjjs** [comment]
> 最新消息，我去试了周杰伦，失败了/(ㄒoㄒ)/~~

用的好快
