### ISSUE TITLE
观演人选择

### ISSUE THREAD

**Issue by Rianlee** [Entromorgan/Autoticket#20]
![image](https://user-images.githubusercontent.com/33619776/67654739-82b13c80-f989-11e9-925d-ce433ab8b342.png)

**Comment by Entromorgan** [comment]
没有看明白你的问题，和观演人有什么关系

**Comment by Rianlee** [comment]
我找到问题了  网速不太好的时候  只能选择不到观影人就提交了 然后就失败了  我在
![image](https://user-images.githubusercontent.com/33619776/67661241-a54c5100-f99b-11e9-8e61-22f709cde395.png)
jia加了一个延迟  就问题能选择到观演人了

**Comment by Entromorgan** [comment]
嗯，加延时是一种workaround，但是放在不同的机器不同的网络环境上效果不一定一样，可能这个时候0.2可以，换一个时候需要0.7，所以我没有统一加上，需要有更好的方法才行
