### ISSUE TITLE
Message: stale element reference: element is not attached to the page document   (Session info: chrome=78.0.3904.70)

### ISSUE THREAD

**Issue by AdventCirno** [Entromorgan/Autoticket#21]
![捕获](https://user-images.githubusercontent.com/30890932/67656422-b773c280-f98e-11e9-9bad-cd8550ea1770.PNG)
然后久自动关闭了，是不是只能用chrome 77

**Comment by Entromorgan** [comment]
和chrome版本没有关系，只要你用对了driver就可以，这个是代码定位稳定性的问题，暂时还没有想到好的方法解决。
