### ISSUE TITLE
能不能抢到大麦网APP的票

### ISSUE THREAD

**Issue by EricTao2** [Entromorgan/Autoticket#3]
如题，很多火爆的演出都只有APP上能购买（网页无法购买），可能是使用的是不同接口，考不考虑支持购买APP上的门票

**Comment by Entromorgan** [comment]
这种代码都是外挂性质的，抢票比手动快，就这套代码直接搬去安卓端是不大可能，应该要单独重写，比如用Autojs（脚本语言）或者java（做成APP），直接跑在手机上。你可以研究一下别的repo有没有类似的功能……我短期估计不会去做这个，希望对你有帮助
