### ISSUE TITLE
selenium

### ISSUE THREAD

**Issue by Justinhol** [Entromorgan/Autoticket#32]
PS H:\ticket\Autoticket-master> python Autoticket.py
Traceback (most recent call last):
  File "Autoticket.py", line 8, in <module>
    from selenium import webdriver
ImportError: No module named selenium

PS H:\ticket\Autoticket-master> pip install selenium
Requirement already satisfied: selenium in d:\software\python\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in d:\software\python\lib\site-packages (from selenium) (1.25.8)

他说没有selenium,然后我安装了啊,这个怎么解决?

**Comment by Entromorgan** [comment]
你用python -m pip install selenium试试，有可能没装在同一个版本下面

**Comment by Justinhol** [comment]
已解决,用Pycharm运行发现chromedriver的版本和我chrome的版本不同,下载了最新的chromedriver已成功运行并购票成功,谢谢大佬
