### ISSUE TITLE
请问运行之后自动跳出的网页图片都不不显示是怎么回事呀

### ISSUE THREAD

**Issue by villainousx** [Entromorgan/Autoticket#33]
***错误：实名信息框未显示，请检查网络或配置文件***
然后就自动退出了
但是正常手动进去是正常的

**Comment by Entromorgan** [comment]
图片不显示是在代码里配置的，为了提高刷新的速度。如果确认配置都没有问题，那在定位实名信息框的代码前面加一点延迟试试

**Comment by villainousx** [comment]
> 图片不显示是在代码里配置的，为了提高刷新的速度。如果确认配置都没有问题，那在定位实名信息框的代码前面加一点延迟试试

请问可以给个例子吗 不会python...谢谢！

**Comment by villainousx** [comment]
> 图片不显示是在代码里配置的，为了提高刷新的速度。如果确认配置都没有问题，那在定位实名信息框的代码前面加一点延迟试试

好像也不是延迟的问题…连头像都没加载出来 cookie是正常扫码登录获取的 应该也没问题呀

**Comment by Entromorgan** [comment]
我回答的是两个问题，图片不显示是因为代码里这么设置了。
加延迟是解决实名信息框不显示的可能方案。

**Comment by Entromorgan** [comment]
如果你只是要显示图片，注释掉代码104，105行（Chrome浏览器）或者109行（FireFox浏览器）。注释方法是在那一行前面加一个英文的“#”。

**Comment by villainousx** [comment]
> 我回答的是两个问题，图片不显示是因为代码里这么设置了。
> 加延迟是解决实名信息框不显示的可能方案。

明白了！不好意思没注意看 可以请教一下延迟要怎么加吗

**Comment by villainousx** [comment]
好的好的 感谢！！ 原来是我测试选了个不用实名的…
