### ISSUE TITLE
piao.damai.cn... 是不是不能用

### ISSUE THREAD

**Issue by davien** [Entromorgan/Autoticket#4]
请教个问题，https://piao.damai.cn/177774.html?spm=a2oeg.search_category.0.0.1aef4d15hVOY07&&clicktitle=2019%E8%B4%B9%E7%8E%89%E6%B8%85%E5%91%8A%E5%88%AB%E6%BC%94%E5%94%B1%E4%BC%9A-%E5%8C%97%E4%BA%AC%E7%AB%99 是不是不能抢，只能抢detail.damai.cn的

**Comment by Entromorgan** [comment]
这个页面肯定是不行的，看格式和我写在模板里的也不一样，不过可以有针对性的修改一下~

**Comment by Entromorgan** [comment]
现在已经部分支持这种格式的页面，可能不是十分完善。
