### ISSUE TITLE
请教一个问题  不知道怎么突然出现这个

### ISSUE THREAD

**Issue by kyo77** [Entromorgan/Autoticket#5]
Message: The element reference of <div class="perform__order__select"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

**Comment by Entromorgan** [comment]
这个错我没遇到过，看字面意思应该是某个用页面元素（title、Xpath或class name）索引的东西失效了，找不到，你是怎么遇到这个问题的？

**Comment by kyo77** [comment]
我就是在提交订单页面 卡了以后看了一眼输出台 就出现了这个

Entromorgan <notifications@github.com>于2019年8月8日 周四下午4:11写道：

**Comment by Entromorgan** [comment]
你的目标网址是啥，我试试

**Comment by kyo77** [comment]
https://detail.damai.cn/item.htm？spm=a2oeg.home.searchtxt.ditem_0.591b23e14JBk6q&id=600588563268 但是 现在380面值的没有了

**Comment by Entromorgan** [comment]
很奇怪啊，我打不开这个链接……你直接告诉我是哪个人的哪场吧

**Comment by kyo77** [comment]
银联呈献陈绮贞 20周年演唱会－漫漫长夜 Cheer 20 香港站

**Comment by Entromorgan** [comment]
我重新试了一下，发现其实是没有成功载入cookie导致的，你把目录下的cookie.pkl删了重新弄一下，这个错就没有了，不过会有一个新的问题，就是它没有选实名者的选项，代码得稍微改改。加上匹配用户昵称和匹配实名者的部分。

**Comment by kyo77** [comment]
好的 谢谢您  因为我是小白高三的学生 突发奇想才弄的这个 您后面说的那个 改的东西 我不知道该怎么改了 如果您有时间 可以把这个代码完善了吗？要是不行的话等您有时间了  您帮我指点指点  谢谢您

**Comment by Entromorgan** [comment]
没事，我这会儿就把它改了。不用客气，本来我写的也不够完善，感谢你的意见~

**Comment by kyo77** [comment]
谢谢您！如果您改完了 方便通知我一下吗  谢谢您

**Comment by Entromorgan** [comment]
好的

**Comment by Entromorgan** [comment]
已修改完成，请重新查看Readme测试一下

**Comment by kyo77** [comment]
好的  谢谢您

Entromorgan <notifications@github.com>于2019年8月8日 周四下午6:56写道：

**Comment by beijinghaizi** [comment]
我还想请教一下  就是增加票的数量  在哪里更改

Feiyu Ma <beijinghaiziaibeijing@gmail.com>于2019年8月8日 周四下午6:57写道：

**Comment by kyo77** [comment]
好的  谢谢您

Entromorgan <notifications@github.com>于2019年8月9日 周五上午10:25写道：

**Comment by Entromorgan** [comment]
你想加票量吗……

**Comment by kyo77** [comment]
对…就比如一下可以抢两张的那种
Entromorgan <notifications@github.com>于2019年8月9日 周五上午10:47写道：

**Comment by Entromorgan** [comment]
容易的，定位到加票的符号，设一个循环点击固定次数，然后买票的时候可能要选多个观演人什么的

**Comment by kyo77** [comment]
好的  谢谢您  我自己在研究研究   谢谢您的指点

Entromorgan <notifications@github.com>于2019年8月9日 周五上午10:50写道：

**Comment by Entromorgan** [comment]
不客气，我有时间可能也会做一下

**Comment by beijinghaizi** [comment]
好  如果我研究的不到位  可能还需要问您   打扰您了  再次表示感谢

Entromorgan <notifications@github.com>于2019年8月9日 周五上午10:53写道：
