### ISSUE TITLE
请教下另外一种抢票的网页

### ISSUE THREAD

**Issue by kingxyt06** [Entromorgan/Autoticket#6]
https://piao.damai.cn/178826.html?spm=a2o6e.11081723.1329302258.dcarditem_0.40593a038N18CT
像这种如果要改  是改里面那些element吗   大神有空可以帮忙试试吗  我是搞测试的  但是难搞T T

**Comment by Entromorgan** [comment]
对。详情页的几种元素都需要改：场次、票档、抢购按钮；后续的确认订单页可能也要改。如果你这个最后是选座购买的那也没办法，我可以改改看。

**Comment by kingxyt06** [comment]
我应该早点看到你的github的T T   下午就开抢了，应该迟了但还是谢谢

**Comment by Entromorgan** [comment]
下午几点，掌握套路还是很好改的，说不定午饭前就能改完

**Comment by kingxyt06** [comment]
2点开始抢票额

**Comment by Entromorgan** [comment]
我试试

**Comment by kingxyt06** [comment]
谢谢谢谢！

**Comment by Entromorgan** [comment]
勉强改好了，你可以试试……稳定性不一定能保证

**Comment by kingxyt06** [comment]
代码更新上去了吗  我下载下来试试   谢谢谢谢

**Comment by Entromorgan** [comment]
我发现你要买的那场需要身份证实名购票……只能到订单结算页，那里还会要点”选择购票人“，现在这个估计是不行= =。不知道还有没有时间改了

**Comment by kingxyt06** [comment]
![image](https://user-images.githubusercontent.com/35811108/62756870-de1b0f00-baab-11e9-84e4-d382c0fb7018.png)
我运行后  现在就是一直在那个界面刷新抢票是不是  没事还是很感谢你

**Comment by Entromorgan** [comment]
刚我加了几行适配实名购票的，没有测试过，你重新pull一下，说不定能用

**Comment by kingxyt06** [comment]
好的谢谢

**Comment by Entromorgan** [comment]
如果出现list index out of range可能是刷新太快了，可以把sleep里的参数设长一点

**Comment by Entromorgan** [comment]
这里以后可能得改改= =
