### ISSUE TITLE
python3.7并配置环境变量后运行Autoticket.py闪退了，怎么办啊

### ISSUE THREAD

**Issue by hao559** [Entromorgan/Autoticket#9]
大佬你好，我是小白一枚，下载python3.7并配置环境变量后运行Autoticket.py闪退了，怎么办啊

**Comment by Entromorgan** [comment]
终端什么输出都没有？至少应该输出一个“###打开浏览器，进入大麦网###”吧？我的测试环境是Windows 10+Anaconda+Python3.6.2。

**Comment by hao559** [comment]
cmd直接闪退了，不知道咋回事

**Comment by Entromorgan** [comment]
抱歉最近不常上git，您指的闪退是输入了python Autoticket.py以后没有任何反应，然后整个cmd窗口关闭了？还是没有关闭，只是没有任何输出？

**Comment by Zing128** [comment]
可以运行了之后，把目标网址换成别的演唱会就闪退不能运行了，是默认地址不能改了吗

**Comment by Entromorgan** [comment]
可以修改的；还需要修改一下对应的场次、票档和实名者序号，注意不要超过范围，否则可能会导致崩溃；最后改一下用户昵称就行了；票数暂时还没有支持。

**Comment by f8q8** [comment]
怎么设置选座呢？每次到选座就失败了

**Comment by Entromorgan** [comment]
选座没想到好办法自动化，每个会场的形状不一样，页面元素也就不一样，不具有通用性。而且如果要设置选座，就必须提前确定选具体几排几号，提前好像也不能知道会场的具体情况。
